apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-container-escape
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitlab-container-escape
  template:
    metadata:
      labels:
        app: gitlab-container-escape
    spec:
      containers:
        - name: gitlab
          image: docker.io/hacklab/gitlab-escape
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
            - containerPort: 80
            - containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.example.com'
                redis['bind']='127.0.0.1'
                redis['port']=6379
                gitlab_rails['initial_root_password']='Password1!'
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 30
